#!/bin/bash

# Creamos la fecha
/bin/date +"%m-%d-%y %r" >> README

# Definimos la variable de fecha
current_date = date +"%m-%d-%y %r"
action = "Ranktab module"

# Ejecutamos secuencias de GIT
git add -A
git commit -m "Today $current_date perform $action"
